<?php

// Optimization: maintain a single-query-duration cache of published story counts per group
$_vojo_group_published_story_counts = array();

/**
 * Load up helpers
 */
function vojo_init(){
    // load custom blocks
    module_load_include('inc', 'vojo', 'includes/vojo.blocks');  
}

/**
 * Helper function to find out how many stories are published within a group.  This is written
 * to be called by themes and custom panels/blocks if they need to embed the count somewhere.  This
 * manages a qingle-query-duration cache for you.
 */
function vojo_group_published_story_count($group_id) {
    $story_count = 0;
    if(array_key_exists($group_id,$_vojo_group_published_story_counts)){
        $story_count = $_vojo_group_published_story_counts[$group_id];
    } else {
        $results = db_query("SELECT count(n.nid) as story_count 
                         FROM {og_ancestry} as oga, {node} as n
                         WHERE oga.nid=n.nid AND oga.group_nid=$group_id AND n.status=1", $group_id);
        while ($object = db_fetch_object($results)) {
            $story_count = $object->story_count;
        }
        $_vojo_group_published_story_counts[$group_id] = $story_count;
    }
    return $story_count;
}

/**
 * Use this to get the path to an image inside the "img" dir of this module
 */
function _vojo_image_path($imgfile){
    return theme_image(drupal_get_path('module','vojo')."/img/".$imgfile);
}

/**
 * Make sure the email from-address works right
 * @depends return-path
 */
function vojo_mail_alter(&$message){
    $message['headers']['Return-Path'] = "registrar@vojo.co";
}