<?php

/**
 * Load up helpers
 */
function vojo_cdh_monterrey_init(){
    // load custom map styles
    module_load_include('inc', 'vojo_cdh_monterrey', 'includes/vojo_cdh_monterrey.openlayers');  
}

/**
 * Implements hook_jcarousel_skin_info().
 */
function vojo_cdh_monterrey_jcarousel_skin_info() {
  $skins = array();

  $skins['cdhmonterrey'] = array(
    'title' => t('CDH Monterrey'),
    'file' => 'jcarousel_skin/jcarousel-cdhmonterrey.css',
  );

  return $skins;
}